/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axibase_clock_HighResolutionClock */

#ifndef _Included_com_axibase_clock_HighResolutionClock
#define _Included_com_axibase_clock_HighResolutionClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axibase_clock_HighResolutionClock
 * Method:    clock_gettime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_axibase_clock_HighResolutionClock_clock_1gettime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
